version: "3.8"

services:
  backend:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: backend
    env_file:
      - ./.env
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
    - "8000:8000"
    networks:
      backend:


  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:


volumes:
  postgres_data:

networks:
  backend: